import type { NextPage } from 'next'
import Head from 'next/head'
import { Footer, Logo, Navigation } from '../components'
import { Hero, About } from '../sections'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/swc.ico" />
      </Head>
      <Logo />
      <Navigation />
      <Hero />
      <About />
      <Footer />

      <footer></footer>
    </>
  )
}

export default Home
