import type { NextPage } from 'next'
import Head from 'next/head'
import { Logo } from '../components'
import BaseLayout from '../layouts/BaseLayout'
import { Hero, About } from '../sections'
import Contact from '../sections/Contact'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/swc.ico" />
      </Head>
      <BaseLayout>
        <Logo />
        <Hero />
        <About />
        <Contact />
      </BaseLayout>
    </>
  )
}

export default Home
